### ISSUE TITLE
Updating more information about Computer Vision

### ISSUE THREAD

**Issue by Learningcomputers777** [OjasMittal/TechBlogzz#12]
I would like to add about Digital Image Processing which is a subset of Computer Vision.It is used daily in Computer vision too.
It would be very knowledgable if I added about that.
Add Hackoctober fest label.

**Comment by OjasMittal** [comment]
Sure go ahead @Learningcomputers777

**Comment by Learningcomputers777** [comment]
Can you add Hackoctober label
